version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: personality
  api:
    build: ./backend
    volumes:
      - ./backend/db.sqlite3:/app
    container_name: personality-api

networks:
  default:
    external:
      name: docker_host
