version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: personality
    # ports:
    # - 8000:80
  api:
    build: ./backend
    container_name: personality-api
    env_file:
      - ./backend/.env
    # ports:
    # - 8001:80

networks:
  default:
    external:
      name: docker_host
