# Generated by Django 4.1.2 on 2022-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('intr', models.CharField(max_length=255)),
                ('extr', models.CharField(max_length=255)),
                ('ambi', models.CharField(max_length=255)),
            ],
        ),
    ]
